blog/urls.py
from django.urls import path

from .views import (
    home,
    blog_detail,
    blog_of_category,
    category,
    blog_of_tags,
    tag_create,
    blog_create,
)

from .views_cbv import BlogListView, BlogDetailView, BlogCreateView

app_name = 'blog'

urlpatterns = [
    # path('', home, name='home'),
    # path('blog/<int:pk>', blog_detail, name='blog_detail'),
    path('category/<slug:slug>', blog_of_category, name='blog_of_category'),
    path('tag/<slug:slug>', blog_of_tags, name='blog_of_tags'),
    path('category/', category, name='category'),
    path('tag-create/', tag_create, name='tag_create'),
    # path('blog-create/', blog_create, name='blog_create'),
]

url_for_cbv = [
    path('', BlogListView.as_view(), name='home'),
    path('blog/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('blog-create/', BlogCreateView.as_view(), name='blog_create'),
]

urlpatterns += url_for_cbv

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
    # path('accounts/', include("django.contrib.auth.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.text import slugify

from .managers import TagCustumManager


User = get_user_model()

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='nomi')
    slug = models.SlugField('slug', max_length=100, unique=True, blank=True)
    image = models.ImageField('rams', upload_to='category/', null=True, blank=True)
    description = models.TextField('tarif', null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Kategoriya'
        verbose_name_plural = 'Kategoriyalar'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, blank=True)
    is_deleted = models.BooleanField(default=False)

    objects = TagCustumManager()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    views = models.PositiveBigIntegerField(default=0)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tag)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Bloglar'



class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.text

blog/forms.py
from django import forms


from .models import Blog, Tag, Comment

class TagForm(forms.Form):
    name = forms.CharField(max_length=100,
                           help_text="tag name kiriting",
                           label='Tag name',
                           widget=forms.TextInput(attrs={"class": "form-control"})
                           )

class BlogForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({"class": "form-control"})
        self.fields['category'].widget.attrs.update({"class": "form-control"})

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Blog
        fields = ['title', 'description', 'image', 'category', 'tags']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import TagForm, BlogForm, CommentForm
from .models import Blog, Category, Tag


# def categories():
#     return Category.objects.all()

def home(request):
    blogs = Blog.objects.all()
    search = request.GET.get('search')
    if search is not None:
        blogs = blogs.filter(title__icontains=search)
    context = {
        'blogs': blogs,
        # 'categories': categories()
    }
    return render(request, 'blog/home.html', context)


def blog_detail(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        comment = form.save(commit=False)
        comment.blog = blog
        comment.user = request.user
        comment.save()
        return redirect('blog:blog_detail', blog.pk)
    else:
        form = CommentForm()
    context = {
        "blog": blog,
        "form": form,
        # 'categores': categories()
    }
    return render(request, 'blog/blog_detail.html', context)


def blog_of_category(requser, slug):
    category = get_object_or_404(Category, slug=slug)
    blogs = Blog.objects.filter(category=category)

    context = {
        'category': category,
        'blogs': blogs
    }
    return render(requser, 'blog/blog_of_category.html', context)


def category(request):

    return render(request, 'blog/categories.html')


def blog_of_tags(requser, slug):
    tag = get_object_or_404(Tag, slug=slug)
    blogs = Blog.objects.filter(tags=tag)

    context = {
        'tag': tag,
        'blogs': blogs
    }
    return render(requser, 'blog/blog_of_category.html', context)


def tag_create(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            Tag.objects.create(name=name)
            return redirect('blog:home')
        else:
            return redirect('blog:home')
    else:
        form = TagForm()

    context = {
        'form': form
    }
    return render(request, 'blog/tag_create.html', context)

def blog_create(request):
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        user = request.user
        if form.is_valid():
            blog = form.save(commit=False)
            blog.user = user
            blog.save()
            return redirect('blog:blog_detail', blog.pk)
    form = BlogForm()
    context = {
        'form': form
    }
    return render(request, 'blog/blog_create.html', context)

templates/blog/blog_create.html
{% extends 'base.html' %}

{% block title %} Blog create {% endblock %}

{% block content %}

    <h1>Blog create</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p> {{ error }} </p>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <input type="submit", value="Save">
    </form>

{% endblock %}

templates/blog/blog_detail.html
{% extends 'base.html' %}


{% block title %} {{  blog.title }} {% endblock %}

{% block content %}
    {{ text }}
    <hr>
    <h3>{{ blog.title }}</h3>
    <img src="{{  blog.image.url }}">
    <p>{{ blog.description }}</p>
    <p>{{ blog.views }}</p>
    <p>{{ blog.created|date:"Y/m/d h:i" }}</p>

    <hr>

    <div class="row">
    <div class="col-6">
        <p>Comment list</p>
        {% for comment in blog.comments.all %}
            <p>{{ comment.text }}</p>
            <p>{{ comment.user }} | {{ comment.created|date:"Y-m-d h:i" }}</p>
        {% endfor %}
    </div>
    <div class="col-6">
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Save">
        </form>
    </div>

    </div>

{% endblock %}

templates/blog/blog_of_category.html
{% extends 'base.html' %}

{% block title %} {{ category.name }} {% endblock %}

{% block content %}

    <h1>{{ category.name }}</h1>
    <hr>
    <div>
        {% for blog in blogs %}
            <h3><a href="{% url 'blog:blog_detail' blog.pk %}">{{ blog.title|upper }}</a></h3>
            <img src="{{ blog.image.url }}">
            <p>{{ blog.description|truncatewords:20 }}</p>
            <p>{{ blog.created|date:"Y-m-d h:i" }}</p>
            <p>{{ blog.views|default:"Ko'rishlar soni yuq" }}</p>
            <hr>
    {% endfor %}
    </div>

{% endblock %}

templates/blog/blog_of_tags.html
{% extends 'base.html' %}

{% block title %} {{ tag.name }} {% endblock %}

{% block content %}

    <h1>{{ tag.name }}</h1>
    <hr>
    <div>
        {% for blog in blogs %}
            <h3><a href="{% url 'blog:blog_detail' blog.pk %}">{{ blog.title|upper }}</a></h3>
            <img src="{{ blog.image.url }}">
            <p>{{ blog.description|truncatewords:20 }}</p>
            <p>{{ blog.created|date:"Y-m-d h:i" }}</p>
            <p>{{ blog.views|default:"Ko'rishlar soni yuq" }}</p>
            <hr>
    {% endfor %}
    </div>

{% endblock %}

templates/blog/categories.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Category list {% endblock %}

{% block content %}

    <h1>Category list</h1>
    <hr>
    <div>
        {% for category in categories %}
            <h3><a href="{% url 'blog:blog_of_category' category.slug %}">{{ category.name|upper }}</a></h3>
            {% if category.image %}
                <img src="{{ category.image.url }}">
            {% else %}
                <img src="{% static 'img/image_not_found.jpg' %}">
            {% endif %}
            <p>{{ category.description|default:"Description not yet written" }}</p>
            <p>{{ category.blog_set.count }}</p>
            <hr>
    {% endfor %}
    </div>

{% endblock %}

templates/blog/home.html
{% extends 'base.html' %}
{% load uppercase %}

{% block title %} Home Page {% endblock %}

{% block content %}

    <h1>Home page</h1>
{#    <form class="d-flex" method="get">#}
{#        <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search">#}
{#        <button class="btn btn-outline-success" type="submit">Search</button>#}
{#    </form>#}
    <hr>
    <div>
        <form method="get">
            {{ filter.form.as_p }}
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        {% for blog in blogs %}

            <h3><a href="{% url 'blog:blog_detail' blog.pk %}">{{ blog.title|title_to_uppercase }}</a></h3>
            <img src="{{ blog.image.url }}">
            <p>{{ blog.description|truncatewords:20 }}</p>
            <p>{{ blog.created|date:"Y-m-d h:i" }}</p>
            <p>{{ blog.views|default:"Ko'rishlar soni yuq" }}</p>
            <p>{{ blog.category.name }}</p>
            {% for tag in blog.tags.all %}
                {{ tag.name }} |
            {% endfor %}
        {% empty %}
            <p>Ma'lumot topilmadi</p>
            <hr>
        {% endfor %}
    </div>

{% endblock %}

templates/blog/tag_create.html
{% extends 'base.html' %}

{% block title %} Tag create {% endblock %}

{% block content %}

    <h1>Tag create</h1>
    <hr>
    <form method="post">
        {% csrf_token %}
        {{ form.name.label }}
        {{ form.name }}
        {{ form.name.help_text }}
    <input type="submit", value="Save">
    </form>

{% endblock %}