account/urls.py
from django.urls import path

from .views import login_view, logout_view, sign_up, user_profile, change_password, user_profile_edit

app_name = 'account'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', sign_up, name='sign_up'),
    path('profile/', user_profile, name='user_profile'),
    path('password-change/', change_password, name='change_password'),
    path('profile-update/', user_profile_edit, name='user_profile_edit'),
]

blog/urls.py
from django.urls import path

from .views import (
    home,
    blog_detail,
    blog_of_category,
    category,
    blog_of_tags,
    tag_create,
    blog_create,
)

from .views_cbv import BlogListView, BlogDetailView, BlogCreateView

app_name = 'blog'

urlpatterns = [
    # path('', home, name='home'),
    # path('blog/<int:pk>', blog_detail, name='blog_detail'),
    path('category/<slug:slug>', blog_of_category, name='blog_of_category'),
    path('tag/<slug:slug>', blog_of_tags, name='blog_of_tags'),
    path('category/', category, name='category'),
    path('tag-create/', tag_create, name='tag_create'),
    # path('blog-create/', blog_create, name='blog_create'),
]

url_for_cbv = [
    path('', BlogListView.as_view(), name='home'),
    path('blog/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('blog-create/', BlogCreateView.as_view(), name='blog_create'),
]

urlpatterns += url_for_cbv

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
    # path('accounts/', include("django.contrib.auth.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load uppercase %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>

<header>
    {% include 'navbar.html' %}
</header>
<div >
    {% if messages %}
        {% for msg in messages %}
            <p>{{ msg }}</p>
        {% endfor %}
    {% endif %}
</div>
<div class="container">
    <div class="row">
        <div class="col-9">
            {% block content %}

            {% endblock %}
        </div>
        <div class="col-3">
            {% if categories %}
                {% for category in categories %}
                    <div><a href="{% url 'blog:blog_of_category' category.slug %}">{{ category.name }}| {{ category.pk|count_blog }}</a></div>
                {% endfor %}
            {% else %}
            No data
            {% endif %}
            <hr>
            {% if tags %}
                {% for tag in tags %}
                    <div><a href="{% url 'blog:blog_of_tags' tag.slug %}">{{ tag.name }} </a></div>
                {% endfor %}
            {% else %}
            No data
            {% endif %}
        </div>
    </div>
</div>

<footer>
    Footer
</footer>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:category' %}">Categories</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'blog:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Creates
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'blog:blog_create' %}">Blog</a></li>
                        <li><a class="dropdown-item" href="{% url 'blog:tag_create' %}">Tag</a></li>
                    </ul>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:user_profile' %}">{{ user.username }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:sign_up' %}">Sign Up</a>
                </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>